# This is a basic workflow to help you get started with Actions

name: hello world

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hello-world-print:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install R
      - name: Install-R
        uses: r-lib/actions/setup-r@v1
        with:
         r-version: '4.0.4' # The R version to load (if necessary) and use.
      
      
      - run: |
          Rscript -e "install.packages('dplyr', repos = 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest')"
          Rscript -e "install.packages('readr', repos = 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest')"
         
      # Run Script
      - run: Rscript -e load_test.R
      
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          git add tests_today.csv
          git commit -m "update tests_today.csv" || echo "Nothing to update"

